/*
 * Auto-generated by: tigris codegen --backend cmsis-nn
 *
 * Model:   ds_cnn_matched
 * Ops:     12
 * Stages:  1
 * Weights: 20
 * Budget:  65536 bytes
 * XIP:     no
 * Dtype:   int8
 * Kernels: cmsis-nn -> s8_ref fallback
 */

#include <string.h>

#include "tigris_codegen_core.h"
#include "tigris_kernels_cmsis_nn.h"

static tigris_mem_error_t tigris_codegen_allocate_inputs(
    const tigris_plan_t *plan, tigris_mem_t *mem,
    tigris_codegen_input_init_fn init_input, void *user_ctx)
{
    for (uint8_t i = 0; i < plan->header->num_model_inputs; i++) {
        uint16_t tidx = plan->model_inputs[i];
        uint32_t size = plan->tensors[tidx].size_bytes;
        tigris_mem_error_t err = tigris_mem_alloc_slow(mem, tidx, size);
        if (err != TIGRIS_MEM_OK)
            return err;
        if (init_input)
            init_input(mem->tensor_ptrs[tidx], size, tidx, user_ctx);
    }
    return TIGRIS_MEM_OK;
}

tigris_error_t tigris_codegen_load_plan(
    const uint8_t *plan_data, uint32_t plan_len, tigris_plan_t *out_plan)
{
    return tigris_plan_load(plan_data, plan_len, out_plan);
}

tigris_mem_error_t tigris_codegen_init(
    const tigris_plan_t *plan, tigris_mem_t *mem,
    void **tensor_ptrs, uint16_t tensor_capacity,
    void *fast_arena, uint32_t fast_arena_size,
    void *slow_arena, uint32_t slow_arena_size,
    tigris_codegen_input_init_fn init_input, void *user_ctx)
{
    if (plan->header->num_tensors > tensor_capacity)
        return TIGRIS_MEM_ERR_BAD_INDEX;

    /* CMSIS-NN reserves scratch from the previous fast arena.  Release that
     * reservation before reinitializing the arena so repeated reset() calls
     * cannot make scratch alias live activations.  The first reset has no
     * reservation; deinit intentionally returns -1 and is harmless. */
    (void)tigris_cmsis_nn_deinit(mem);

    memset(tensor_ptrs, 0, (size_t)tensor_capacity * sizeof(*tensor_ptrs));
    tigris_mem_error_t err = tigris_mem_init(
        mem, tensor_ptrs, plan->header->num_tensors,
        fast_arena, fast_arena_size, slow_arena, slow_arena_size);
    if (err != TIGRIS_MEM_OK)
        return err;
    uint32_t cmsis_fast_required =
        tigris_cmsis_nn_fast_arena_required(plan);
    if (cmsis_fast_required == UINT32_MAX ||
        fast_arena_size < cmsis_fast_required)
        return TIGRIS_MEM_ERR_OOM;
    if (tigris_cmsis_nn_prepare(plan, mem) != 0)
        return TIGRIS_MEM_ERR_OOM;

    return tigris_codegen_allocate_inputs(plan, mem, init_input, user_ctx);
}

tigris_mem_error_t tigris_codegen_reset(
    const tigris_plan_t *plan, tigris_mem_t *mem,
    tigris_codegen_input_init_fn init_input, void *user_ctx)
{
    if (!plan || !plan->header || !mem || !mem->tensor_ptrs ||
        !mem->fast_base || !mem->slow_base)
        return TIGRIS_MEM_ERR_NULL;

    /* Preserve the backend's reservation. CMSIS-NN reduces fast_size in init;
     * reinitializing with that reduced size keeps scratch disjoint from fresh
     * activation allocations on every inference. */
    tigris_mem_error_t err = tigris_mem_init(
        mem, mem->tensor_ptrs, plan->header->num_tensors,
        mem->fast_base, mem->fast_size, mem->slow_base, mem->slow_size);
    if (err != TIGRIS_MEM_OK)
        return err;
    return tigris_codegen_allocate_inputs(plan, mem, init_input, user_ctx);
}

tigris_kernel_fn tigris_codegen_dispatch(void)
{
    return tigris_dispatch_kernel_cmsis_nn;
}

tigris_exec_error_t tigris_codegen_run(
    const tigris_plan_t *plan, tigris_mem_t *mem, tigris_exec_stats_t *stats,
    tigris_executor_workspace_t *workspace)
{
    return tigris_run_with_workspace(
        plan, mem, tigris_dispatch_kernel_cmsis_nn, NULL, stats, workspace);
}

tigris_exec_error_t tigris_codegen_run_with_workspace_buffer(
    const tigris_plan_t *plan, tigris_mem_t *mem, tigris_exec_stats_t *stats,
    void *workspace, size_t workspace_size)
{
    return tigris_run_with_workspace_buffer(
        plan, mem, tigris_dispatch_kernel_cmsis_nn, NULL, stats, workspace, workspace_size);
}
