#!/usr/bin/env python3
"""Embed a binary file (e.g. a .tgrs plan) as a C byte array.

Emits a const array placed in .rodata (flash on Cortex-M), 8-byte aligned so
the TiGrIS zero-copy loader can cast straight into it.

Usage:
    python bin2c.py model.tgrs model_blob.c --symbol g_tigris_plan
"""

from __future__ import annotations

import argparse
from pathlib import Path


def emit(src: Path, dst: Path, symbol: str) -> int:
    data = src.read_bytes()
    lines = [
        f"/* Generated by tools/bin2c.py from {src.name} - do not edit. */",
        "#include <stddef.h>",
        "",
        f"const unsigned int {symbol}_len = {len(data)}u;",
        "",
        "__attribute__((aligned(16)))",
        f"const unsigned char {symbol}[] = {{",
    ]
    for i in range(0, len(data), 12):
        chunk = data[i : i + 12]
        lines.append("    " + "".join(f"0x{b:02x}, " for b in chunk).rstrip())
    lines.append("};")
    lines.append("")
    dst.write_text("\n".join(lines))
    return len(data)


def main() -> None:
    ap = argparse.ArgumentParser(description="Embed a binary file as a C array")
    ap.add_argument("input", type=Path, help="binary file to embed (e.g. a .tgrs plan)")
    ap.add_argument("output", type=Path, help="C source file to write")
    ap.add_argument("--symbol", default="g_tigris_plan", help="C identifier for the array")
    args = ap.parse_args()

    args.output.parent.mkdir(parents=True, exist_ok=True)
    n = emit(args.input, args.output, args.symbol)
    print(f"bin2c: {args.input} -> {args.output} ({n} bytes as {args.symbol}[])")


if __name__ == "__main__":
    main()
